version: '1'
services:
   wildfly:
      build: ../componnent/wildfly
      ports:
         - "9090:8080"
         - "9990:9990"
      links:
         - mysql:db
   mysql:
      build: ../componnent/mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_ROOT_PASSWORD: admin
      ports:
         - "3306:3306"
   phpmyadmin:
      build: ../componnent/phpmyadmin
      environment:
         PMA_HOST: mysql
         MYSQL_ROOT_PASSWORD: admin
      ports:
         - "6060:80"
      links:
         - mysql:db